
import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Raffaele Ragni <raffaele.ragni@gmail.com>
 */
public class SetBEForm extends javax.swing.JFrame
{
    /** Creates new form SetBEForm */
    public SetBEForm()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        BE_Long = new javax.swing.JFormattedTextField();
        BE_Lat = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Change BE");
        setAlwaysOnTop(true);

        try
        {
            BE_Long.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ## ##")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }
        BE_Long.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                BE_LongKeyPressed(evt);
            }
        });

        try
        {
            BE_Lat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ## ##")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }
        BE_Lat.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                BE_LatKeyPressed(evt);
            }
        });

        jLabel1.setText("LAT");

        jLabel2.setText("LON");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LL coordinates in (XX YY ZZ), space separated");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BE_Lat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel))
                            .addComponent(BE_Long))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BE_Lat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BE_Long, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOKActionPerformed
    {//GEN-HEADEREND:event_btnOKActionPerformed
        setVisible(false);
        String sLong = BE_Long.getText();
        String sLat = BE_Lat.getText();
        String[] ssLong = sLong.replaceAll("[^0-9\\s]", "").split("\\s");
        String[] ssLat = sLat.replaceAll("[^0-9\\s]", "").split("\\s");
        try
        {
            double beX = Double.parseDouble(ssLong[0]) + ((Double.parseDouble(ssLong[1]) + (Double.parseDouble(ssLong[2]) / 60)) / 60);
            double beY = Double.parseDouble(ssLat[0]) + ((Double.parseDouble(ssLat[1]) + (Double.parseDouble(ssLat[2]) / 60)) / 60);
            Main.main.status.setBe(beX, beY);
        }
        catch (Exception e){}
    }//GEN-LAST:event_btnOKActionPerformed

    private void BE_LatKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BE_LatKeyPressed
    {//GEN-HEADEREND:event_BE_LatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnOKActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            btnCancelActionPerformed(null);
    }//GEN-LAST:event_BE_LatKeyPressed

    private void BE_LongKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BE_LongKeyPressed
    {//GEN-HEADEREND:event_BE_LongKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnOKActionPerformed(null);
        else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE)
            btnCancelActionPerformed(null);
    }//GEN-LAST:event_BE_LongKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField BE_Lat;
    private javax.swing.JFormattedTextField BE_Long;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
